### ISSUE TITLE
这个项目是如何实现注意力机制的呢

### ISSUE THREAD

**Issue by thestudyofdl** [XD-mu/Bacterial-Atlas-Identification-Model-Based-on-AM-CNN#1]
看了好久也没在代码职工发现 希望楼主大大可以解答一下

**Comment by XD-mu** [comment]
你好，由于目前该项目并未完结且与负责人签订协议，这里我并没有给出最终的训练网络核心代码，而是只给出了之前训练过程中调整卷积神经网络的架构，希望能理解一下。
